# Generated by Django 3.0.3 on 2020-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200226_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(choices=[('pt', 'Заочная'), ('ft', 'Очная')], default='ft', max_length=3),
        ),
    ]
