# Generated by Django 3.0.3 on 2020-02-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200226_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='tax',
            field=models.FloatField(default=0.13),
        ),
    ]
