# Generated by Django 3.0.3 on 2020-02-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200226_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='employee',
        ),
        migrations.AddField(
            model_name='income',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='company.Employee'),
            preserve_default=False,
        ),
    ]
