# Generated by Django 3.0.3 on 2020-02-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200226_0716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
