# Generated by Django 3.0.3 on 2020-02-26 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_delete_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField(default=0.13)),
                ('salary', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Оклад не меньше 0')])),
                ('percent', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(limit_value=1, message='Максимальное значение 1'), django.core.validators.MinValueValidator(limit_value=0, message='Минимальное значение 0')])),
                ('premium', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Премия не меньше 0')])),
                ('income_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='company.Employee')),
            ],
            managers=[
                ('total', django.db.models.manager.Manager()),
            ],
        ),
    ]
