# Generated by Django 3.0.3 on 2020-02-26 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=40000, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Оклад не меньше 0')]),
            preserve_default=False,
        ),
    ]
