# Generated by Django 3.0.3 on 2020-02-26 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200226_0733'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='income',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(limit_value=1, message='Максимальное значение 1'), django.core.validators.MinValueValidator(limit_value=-0.5, message='Минимальное значение -0.5')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='premium',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Премия не меньше 0')]),
        ),
    ]
