# Generated by Django 3.0.4 on 2020-03-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_education_faculty_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxes',
            new_name='Tax',
        ),
        migrations.AlterField(
            model_name='child',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduate_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attitude_to_conscription',
            field=models.CharField(choices=[('pos', 'Позитивное'), ('neu', 'Нейтральное'), ('neg', 'Негативное')], default='neu', max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
