# Generated by Django 3.0.5 on 2020-04-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_employee_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname']},
        ),
    ]
