# Generated by Django 3.0.5 on 2020-04-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20200406_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department', 'surname', 'name', 'patronymic']},
        ),
    ]
